<?php

namespace Yoda\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Symfony\Component\Security\Core\User\User;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $username
     * @return User
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOnebyUserNameOrEmail($username){
        return $this->createQueryBuilder('u')
            ->andWhere('u.username = :username OR u.email= :email')
            ->setParameter('username',$username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    
}
