event_event:
    resource: "@EventBundle/Controller/EventController.php"
    type:     annotation

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /
login_form:
  path: /login/
  defaults: {_controller: UserBundle:Security:login}
login_check:
  path: /check/
  defaults: {_controller: UserBundle:Security:loginCheck}
logout:
    path: /logout

register_form:
  path: /register/
  defaults: {_controller: UserBundle:Register:register}

event_attend:
  path: /{id}/attend.{format}
  defaults: {_controller: "EventBundle:Event:attend", format: json}
  requirements:
      format: json

event_unattend:
  path: /{id}/unattend.{format}
  defaults: {_controller: "EventBundle:Event:unattend", format: json}
  requirements:
        format: json